### ISSUE TITLE
Can we still use the smee proxy with serverless offline? 

### ISSUE THREAD

**Issue by jakebolam** [probot/adapter-aws-lambda-serverless#10]

**Comment by jakebolam** [comment]
Should we actually port all the config from probot-run ? https://github.com/probot/probot/blob/master/bin/probot-run.js#L24-L31

tldr: Some don't work the same on serverless-lambda

**Comment by jakebolam** [comment]
Maybe need a serverless-plugin for this. Like the `.env` one which coincidentally would be good for this project too! https://github.com/colynb/serverless-dotenv-plugin

**Comment by jakebolam** [comment]
Happy to the make plugin!

**Comment by gr2m** [comment]
With https://github.com/probot/adapter-aws-lambda-serverless/pull/59, you can continue to start your probot application function using `probot run ./app.js` which also supports the smee proxy. That should cover most use cases?
