### ISSUE TITLE
Bad Gateway for probot routes

### ISSUE THREAD

**Issue by riyadhalnur** [probot/adapter-aws-lambda-serverless#24]
The `/stats/` and `/ping` routes for a probot application return an **HTTP 502 Bad Gateway** status.

The application, in this case, is a lambda function triggered by AWS ALB - the routes forwarded are `/`, `/probot`, `/probot/stats`, and `/ping`. Only the `/probot` route works since it is handled directly by the handler in this module https://github.com/probot/serverless-lambda/blob/master/index.js#L31-L40.

**Comment by gr2m** [comment]
Starting with https://github.com/probot/adapter-aws-lambda-serverless/pull/59, no other routes will be exposed by default, you have to that yourself.
