### ISSUE TITLE
Allow custom log function to be provided

### ISSUE THREAD

**Issue by Limess** [probot/adapter-aws-lambda-serverless#25]
Currently this library logs using `console` methods. 

We're using structured logging in JSON using a library (Pino but that's not relevant here) in all of our applications, including AWS Lambda functions. Using this library currently results in unstructured log statements in our log aggregation which makes queries difficult.

I'd suggest adding a `logger` parameter to an `options` object and then calling that instead of `console`, defaulting to `console` if none is provided.

e.g. 

```js
serverless(handler, {logger});
```

where `logger` has the same interface as `console`.

**Comment by gr2m** [comment]
This will be possible via https://github.com/probot/adapter-aws-lambda-serverless/pull/59

```js
const { createLambdaFunction, createProbot } = require("@probot/adapter-aws-lambda-serverless");
const appFn = require("./");

module.exports.webhooks = createLambdaFunction(appFn, {
  probot: createProbot({
    defaults: { 
      log: logger
    }
  })
});
```

Also with Probot v11, Probot itself is using pino, too :) We created a custom transport: https://github.com/probot/pino/
