### ISSUE TITLE
Fails in case of AWS Lambda cold start

### ISSUE THREAD

**Issue by Arshadf** [probot/adapter-aws-lambda-serverless#29]
I have used this extension to deploy my Probot on Lambda, my use case is I want to trigger the build on Travis CI when I add a comment on Pull Request. My issue is when I add a comment on a PR for the first time or after a while like 1 hour, it doesn't trigger the build and when the lambda resources are available or after the first failed try it triggers the build successfully.

Its my first issue, so be cool if I haven't provided sufficient details

**Comment by gr2m** [comment]
As nobody else reported the same issue, I assume it was unique to your use case. Have you been able to resolve it?

**Comment by chriskilding** [comment]
I too have experienced this problem - please could the issue be reopened?

I have my Probot chatbot app deployed on Lambda using a typical SAM project setup: GitHub -> API Gateway -> Lambda.

When the Probot app hasn't been used for a while, Lambda must cold start an instance of the app. The cold start often takes longer than GitHub's webhook dispatcher is willing to wait, so it times out and doesn't redeliver the event.

**Comment by chriskilding** [comment]
The queue solution feels like a generic pattern that could be used in a lot of cases. Would `adapter-aws-lambda-serverless` need to be modified to handle webhook events coming from SQS rather than API Gateway, or is it able to handle events no matter their source?

**Comment by chriskilding** [comment]
Another solution would be to use Lambda Provisioned Concurrency to keep at least 1 instance of the Probot app warm at all times. This is operationally simpler to deploy than the queue, but it (a) costs money on an ongoing basis and (b) won't deal with usage spikes when extra instances of the Probot app need to start - they'll be cold starting, and there will be timeouts.

So I don't like it as much as the queue option.
