### ISSUE TITLE
Provide GitHub Authentication variables programatically

### ISSUE THREAD

**Issue by smolster** [probot/adapter-aws-lambda-serverless#54]
Is there any plan to support providing GitHub credential information (`APP_ID`, `WEBHOOK_SECRET`, `PRIVATE_KEY`) _without_ environment variables? 

For example, something like:

```javascript
const { serverless } = require('@probot/serverless-lamda');

module.exports.probot = serverless({
  app: myAppFn,
  getAuthentication: () => {
     // retrieve values, and return e.g.
    return { appId, privateKey, webhookSecret };
  }
})
```

Thanks!

**Comment by gr2m** [comment]
Yes! The latest Probot ships with new APIs that should make it easier to use in serverless/function environments. This is how the APIs look like:

https://probot.github.io/docs/serverless-deployment/#deploy-the-app

What that work for you?

The timing of your question is great! I'm looking for someone to help create an example repository for an AWS Lambda deployment, similar to https://github.com/probot/example-google-cloud-function. Would you like to help with that? I wonder what the most minimal setup would be to (continuously) deploy a Probot app function to AWS Lambda. I wonder if we need the serverless framework or if there is a simpler way without the extra tooling?

**Comment by gr2m** [comment]
It will be possible via https://github.com/probot/adapter-aws-lambda-serverless/pull/59

using environment variables:

```js
const { createLambdaFunction, createProbot } = require("@probot/adapter-aws-lambda-serverless");
const appFn = require("./");
module.exports.webhooks = createLambdaFunction(appFn, { probot: createProbot() });
```

programmatic

```js
const { createLambdaFunction, Probot } = require("@probot/adapter-aws-lambda-serverless");
const appFn = require("./");
module.exports.webhooks = createLambdaFunction(appFn, { 
  probot: new Probot({
    // pass whatever options you like
    appId,
    privateKey,
    secret,
  })
});
```
