### ISSUE TITLE
Headers case-insensitivity

### ISSUE THREAD

**Issue by axel3rd** [probot/adapter-aws-lambda-serverless#62]
https://github.com/probot/adapter-aws-lambda-serverless/blob/d126582a12aa54776d34e8bfccdc8ce41f7df3b9/lambda-function.js#L11-L14

From [RFC 7230 > 3.2.  Header Fields](https://tools.ietf.org/html/rfc7230#section-3.2):

> Each header field consists of a case-insensitive field name followed by a colon (":"), optional leading whitespace, the field value, and optional trailing whitespace.

=> If you are testing (sample #61) your Lambda Probot with some tools which can "rewrite" headers (sample: [Ansible URI module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/uri_module.html)) like that (in Camel Case):

```
X-Github-Delivery: fake-ansible
X-Github-Event: test
```
*Note the 'h' in lowercase*

It doesn't work 😢. It would be nice if *adapter-aws-lambda-serverless* could be **headers case-insensitive**.

Error detail:
```
INFO	AggregateError: 
    Error: Event name not passed
        at Array.map (<anonymous>)
        at receiverHandle (/var/task/node_modules/@octokit/webhooks/dist-node/index.js:98:11)
        at verifyAndReceive (/var/task/node_modules/@octokit/webhooks/dist-node/index.js:307:29)
        at lambdaFunction (/var/task/node_modules/@probot/adapter-aws-lambda-serverless/lambda-function.js:12:24)
        at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)
    at receiverHandle (/var/task/node_modules/@octokit/webhooks/dist-node/index.js:98:11)
    at verifyAndReceive (/var/task/node_modules/@octokit/webhooks/dist-node/index.js:307:29)
    at lambdaFunction (/var/task/node_modules/@probot/adapter-aws-lambda-serverless/lambda-function.js:12:24)
    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)
```
*NB: False line number, console.log added for debug*

**Comment by gr2m** [comment]
> It would be nice if _adapter-aws-lambda-serverless_ could be **headers case-insensitive**

I know, I agree, but there is no efficient way to lowercase all headers. Because we know the source of the request, I thought it would be safe to access the headers with the casing we know is sent by GitHub, plus lowercase just to be sure.

> If you are testing (sample #61) your Lambda Probot with some tools which can "rewrite" headers (sample: [Ansible URI module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/uri_module.html)) like that (in Camel Case):

The docs says

> The module returns all the HTTP headers in lower-case

I don't get it. Why would `X-GitHub-Delivery` be changed to `X-Github-Delivery`?

**Comment by axel3rd** [comment]
> The docs says: The module returns all the HTTP headers in lower-case

Yes, but it is not true 😆.

> I don't get it. Why would X-GitHub-Delivery be changed to X-Github-Delivery?

I don't searched why in Ansible code, but all headers are written in Camel-case (even if not modified in debug log ... spent lot of time to catch it).
Camel-case seems a common usage for HTTP headers (`Content-Type`, ...) even if should be considered insensitively.

> but there is no efficient way to lowercase all headers

Is it more complex than searching LowerCase value in an Array 🤔 ? I was started to work on it.

**Comment by gr2m** [comment]
> > The docs says: The module returns all the HTTP headers in lower-case
> 
> Yes, but it is not true 😆.

maybe send a PR to their docs?

We could use https://github.com/sindresorhus/lowercase-keys, it's a simple function, but it copies the entire headers object. 

Maybe we should just do it and safe us more headache in future

**Comment by axel3rd** [comment]
> maybe send a PR to their docs?

👍 (Need a simple test to proof it)

> Maybe we should just do it and safe us more headache in future

I will have a look on headers it (values should not be modified).

**Comment by axel3rd** [comment]
>>  The docs says: The module returns all the HTTP headers in lower-case
>
> maybe send a PR to their docs?

To be precise, the doc speaks about **reponse** headers, enforced in lowercase (verified), but nothing about request headers. PR: [#73702](https://github.com/ansible/ansible/pull/73702)

**Comment by gr2m** [comment]
okay let's use https://github.com/sindresorhus/lowercase-keys to be safe.

**Comment by axel3rd** [comment]
Tested in real life (Ansible smoke tests, probot deployment, ...) / LGTM 👍
