### ISSUE TITLE
Get rid of `action/cache` in `workflows/test.yml`

### ISSUE THREAD

**Issue by oscard0m** [probot/adapter-aws-lambda-serverless#73]
Would have sense to remove this step after adding `cache` option to `setup-node` ?

https://github.com/probot/adapter-aws-lambda-serverless/blob/1429700be65b65bd0037c9038f4d6c64a995fc67/.github/workflows/test.yml#L27-L33

**Comment by gr2m** [comment]
Yes 👍🏼
